[project]
name = "keyzen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogluon-tabular[all]>=1.5.0",
    "deap>=1.4.3",
    "ipdb>=0.13.13",
    "simpy>=4.1.1",
    "torch>=2.9.1",
    "wand>=0.6.13",
]
